/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instrument;

public class piano_itself extends javax.swing.JFrame {

    public piano_itself() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        w1 = new javax.swing.JButton();
        w2 = new javax.swing.JButton();
        w3 = new javax.swing.JButton();
        w4 = new javax.swing.JButton();
        w5 = new javax.swing.JButton();
        w6 = new javax.swing.JButton();
        w7 = new javax.swing.JButton();
        w8 = new javax.swing.JButton();
        w9 = new javax.swing.JButton();
        w10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setText("W");
        b1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 30, 124));

        b2.setText("E");
        b2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 30, 124));

        b3.setText("T");
        b3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 120, 30, 124));

        b4.setText("Y");
        b4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 120, 30, 124));

        b5.setText("U");
        b5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 30, 124));

        b6.setText("O");
        b6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 120, 30, 124));

        b7.setText("P");
        b7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 30, 124));

        w1.setText("A");
        w1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1ActionPerformed(evt);
            }
        });
        getContentPane().add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 43, 185));

        w2.setText("S");
        w2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2ActionPerformed(evt);
            }
        });
        getContentPane().add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 43, 185));

        w3.setText("D");
        w3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w3ActionPerformed(evt);
            }
        });
        getContentPane().add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 43, 185));

        w4.setText("F");
        w4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w4ActionPerformed(evt);
            }
        });
        getContentPane().add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 43, 185));

        w5.setText("G");
        w5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w5ActionPerformed(evt);
            }
        });
        getContentPane().add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 43, 185));

        w6.setText("H");
        w6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w6ActionPerformed(evt);
            }
        });
        getContentPane().add(w6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 43, 185));

        w7.setText("J");
        w7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w7ActionPerformed(evt);
            }
        });
        getContentPane().add(w7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 43, 185));

        w8.setText("K");
        w8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w8ActionPerformed(evt);
            }
        });
        getContentPane().add(w8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 43, 185));

        w9.setText("L");
        w9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w9ActionPerformed(evt);
            }
        });
        getContentPane().add(w9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 43, 185));

        w10.setText(";");
        w10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        w10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w10ActionPerformed(evt);
            }
        });
        getContentPane().add(w10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 43, 185));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w1ActionPerformed

    private void w3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w3ActionPerformed

    private void w2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w2ActionPerformed

    private void w6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w6ActionPerformed

    private void w5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w5ActionPerformed

    private void w4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w4ActionPerformed

    private void w7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w7ActionPerformed

    private void w9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w9ActionPerformed

    private void w10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w10ActionPerformed

    private void w8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_w8ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(piano_itself.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(piano_itself.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(piano_itself.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(piano_itself.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new piano_itself().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton w1;
    private javax.swing.JButton w10;
    private javax.swing.JButton w2;
    private javax.swing.JButton w3;
    private javax.swing.JButton w4;
    private javax.swing.JButton w5;
    private javax.swing.JButton w6;
    private javax.swing.JButton w7;
    private javax.swing.JButton w8;
    private javax.swing.JButton w9;
    // End of variables declaration//GEN-END:variables
}
